[phases.setup]
nixPkgs = ['python39', 'postgresql']

[phases.install]
cmds = ['cd backend && pip install -r requirements.txt']

[phases.build]
cmds = [
  'cd backend && python manage.py collectstatic --noinput',
  'cd backend && python manage.py migrate --noinput'
]

[start]
cmd = 'cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT'