# Generated by Django 4.2.21 on 2025-06-15 12:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین به\u200cروزرسانی"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد خرید",
                "verbose_name_plural": "سبدهای خرید",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام کامل (صورتحساب)"
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="ایمیل (صورتحساب)"
                    ),
                ),
                (
                    "billing_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تلفن (صورتحساب)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت سفارش"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین به\u200cروزرسانی"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="مبلغ کل",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت/تایید"),
                            ("processing", "در حال پردازش"),
                            ("confirmed", "تایید شده/پرداخت شده"),
                            ("completed", "تکمیل شده (اقامت انجام شد)"),
                            ("cancelled", "لغو شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت سفارش",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شناسه تراکنش پرداخت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش (رزرو)",
                "verbose_name_plural": "سفارش\u200cها (رزروها)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="تعداد (معمولا 1 برای رزرو)"
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="تاریخ ورود")),
                ("check_out_date", models.DateField(verbose_name="تاریخ خروج")),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(verbose_name="تعداد مهمانان"),
                ),
                (
                    "full_name_booking",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نام کامل رزرو کننده",
                    ),
                ),
                (
                    "email_booking",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل رزرو کننده",
                    ),
                ),
                (
                    "phone_number_booking",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره تلفن رزرو کننده",
                    ),
                ),
                (
                    "price_per_night_at_order",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="قیمت هر شب (در زمان سفارش)",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="cart.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "property_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items_property",
                        to="shop.property",
                        verbose_name="ملک (خانه)",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش (رزرو)",
                "verbose_name_plural": "آیتم\u200cهای سفارش (رزروها)",
                "ordering": ["order", "property_item"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="تعداد (معمولا 1 برای رزرو)"
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="تاریخ ورود")),
                ("check_out_date", models.DateField(verbose_name="تاریخ خروج")),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        default=1, verbose_name="تعداد مهمانان"
                    ),
                ),
                (
                    "full_name_booking",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نام کامل رزرو کننده",
                    ),
                ),
                (
                    "email_booking",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ایمیل رزرو کننده",
                    ),
                ),
                (
                    "phone_number_booking",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره تلفن رزرو کننده",
                    ),
                ),
                (
                    "price_per_night_at_booking",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="قیمت هر شب (در زمان افزودن به سبد)",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ اضافه شدن"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                        verbose_name="سبد خرید",
                    ),
                ),
                (
                    "property_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="shop.property",
                        verbose_name="ملک (خانه)",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سبد خرید (رزرو)",
                "verbose_name_plural": "آیتم\u200cهای سبد خرید (رزروها)",
                "ordering": ["-added_at"],
                "unique_together": {
                    ("cart", "property_item", "check_in_date", "check_out_date")
                },
            },
        ),
    ]
